version: "3.8"

services:
  backend:
    build:
      context: ./server
      dockerfile: ./docker/prod.dockerfile
    container_name: it-profile__prod-server
    networks:
      server-database:
        ipv4_address: 178.70.200.2

      client-server:
        ipv4_address: 178.70.100.2

    environment:
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: password
      MONGODB_URL: mongodb://178.70.200.3:27017/

    depends_on:
      - database

  frontend:
    build:
      context: ./client
      dockerfile: ./docker/prod.dockerfile

    container_name: it-profile__prod-client

    ports:
      - 8080:8080

    networks:
      - client-server

    depends_on:
      - backend

  database:
    image: mongo
    container_name: it-profile__prod-database
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

    networks:
      server-database:
        ipv4_address: 178.70.200.3

    ports:
      - 57017:21017

networks:
  server-database:
    name: server-database
    driver: bridge
    ipam:
      config:
        - subnet: 178.70.200.0/24
          gateway: 178.70.200.1

  client-server:
    name: client-server
    driver: bridge
    ipam:
      config:
        - subnet: 178.70.100.0/24
          gateway: 178.70.100.1
